### ISSUE TITLE
Websocket enotfound

### ISSUE THREAD

**Issue by Shadowstep33** [escwdev/kucoin-node-api#9]
Hi, i'm getting this error when I try to init a websocket:

```
{ Error: getaddrinfo ENOTFOUND push1-v2.kucoin.com push1-v2.kucoin.com:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'push1-v2.kucoin.com',
  host: 'push1-v2.kucoin.com',
  port: 80 }
```

**Comment by escwdev** [comment]
Merged your pull request. Thanks.

**Comment by Shadowstep33** [comment]
Np, thank you for the package @escwdev ! I'll likely have one more PR for an error I found for WS connections that seems to be uncatchable but will probs be a while on that

**Comment by escwdev** [comment]
I'm actually writing the wrapper in Rust right now and have noticed some aspects that can be better designed for the websocket module (i.e. easy way to do multiple subscriptions to the same socket for the end user). 

Implementing that would require a bit of re-design but I've had a custom version that enables this for awhile so I may be able to port/make some changes to that and potentially look into implementing Kucoin's form of multiplexing; but that may be a awhile as well since I have a number of other things that take priority.

Happy to have contributions though and I'll do what I can to quickly review/implement pull requests.

Cheers!
